# modules/ai/litellm/generate-config.nix
# Generates LiteLLM config.yaml from models.json + providers-enabled.json

{ config, lib, pkgs, ... }:

let
  dataDir = "/srv/appdata/litellm";

  generateConfig = pkgs.writeShellScript "litellm-generate-config" ''
    export PATH="${lib.makeBinPath [ pkgs.jq pkgs.coreutils ]}:$PATH"

    MODELS_FILE="${dataDir}/models.json"
    ENABLED_FILE="${dataDir}/providers-enabled.json"
    CONFIG_FILE="${dataDir}/config.yaml"

    # Skip if models.json doesn't exist yet (first build)
    if [ ! -f "$MODELS_FILE" ]; then
      echo "litellm-generate-config: $MODELS_FILE not found, skipping"
      exit 0
    fi

    # Create default providers-enabled.json if missing (all providers enabled)
    if [ ! -f "$ENABLED_FILE" ]; then
      echo '{}' > "$ENABLED_FILE"
      echo "litellm-generate-config: created default $ENABLED_FILE"
    fi

    # Read enabled providers
    ENABLED=$(cat "$ENABLED_FILE")

    # If enabled list is empty ({}), include all models
    # Otherwise, filter by provider prefix
    if [ "$ENABLED" = "{}" ]; then
      MODELS=$(cat "$MODELS_FILE")
    else
      MODELS=$(jq --argjson enabled "$ENABLED" '
        [.[] | select(
          (.litellm_params.model | split("/")[0]) as $provider |
          ($enabled | has($provider)) and ($enabled[$provider] == true)
        )]
      ' "$MODELS_FILE")
    fi

    MODEL_COUNT=$(echo "$MODELS" | jq 'length')

    if [ "$MODEL_COUNT" -eq 0 ]; then
      echo "litellm-generate-config: WARNING — no models after filtering"
      echo "litellm-generate-config: enabled providers: $ENABLED"
      exit 1
    fi

    # Generate config.yaml
    {
      echo "# Auto-generated by litellm-generate-config"
      echo "# Do not edit manually — managed by providers-enabled.json"
      echo ""
      echo "model_list:"
      echo "$MODELS" | jq -r '.[] |
        "  - model_name: \(.model_name)\n    litellm_params:\n      model: \(.litellm_params.model)\n      api_base: \(.litellm_params.api_base)\n      api_key: \(.litellm_params.api_key)"
      '
      echo ""
      echo "litellm_settings:"
      echo "  json_logs: true"
      echo "  drop_params: true"
      echo ""
      echo "general_settings:"
      echo "  master_key: os.environ/LITELLM_MASTER_KEY"
    } > "$CONFIG_FILE"

    echo "litellm-generate-config: wrote $CONFIG_FILE with $MODEL_COUNT models"
  '';

in
{
  environment.systemPackages = [ generateConfig ];
}
