# modules/ai/litellm/renderer.nix
# Renders LiteLLM config.yaml from models.json + providers-enabled.json
# Owns: generateConfig script, ExecStart override, ExecStartPre, ReadWritePaths

{ config, lib, pkgs, ... }:

let
  state = config.litellm.state;

  generateConfig = pkgs.writeShellScript "litellm-generate-config" ''
    umask 0022
    export PATH="${lib.makeBinPath [ pkgs.jq pkgs.coreutils ]}:$PATH"

    MODELS_FILE="${state.modelsJson}"
    ENABLED_FILE="${state.providersEnabledJson}"
    CONFIG_FILE="${state.configYaml}"

    # Skip if models.json doesn't exist yet (first build)
    if [ ! -f "$MODELS_FILE" ]; then
      echo "litellm-generate-config: $MODELS_FILE not found, skipping"
      exit 0
    fi

    # Create default providers-enabled.json if missing (empty = all enabled)
    if [ ! -f "$ENABLED_FILE" ]; then
      echo '{}' > "$ENABLED_FILE"
      echo "litellm-generate-config: created default $ENABLED_FILE"
    fi

    # Read enabled providers
    ENABLED=$(cat "$ENABLED_FILE")

    # If enabled list is empty ({}), include all models
    # Otherwise, filter by provider prefix
    if [ "$ENABLED" = "{}" ]; then
      MODELS=$(cat "$MODELS_FILE")
    else
      MODELS=$(jq --argjson enabled "$ENABLED" '
        [.[] | select(
          (.model_name | split("/")[0]) as $provider |
          ($enabled | has($provider)) and ($enabled[$provider] == true)
        )]
      ' "$MODELS_FILE")
    fi

    MODEL_COUNT=$(echo "$MODELS" | jq 'length')

    if [ "$MODEL_COUNT" -eq 0 ]; then
      echo "litellm-generate-config: ERROR — no models after filtering"
      echo "litellm-generate-config: enabled providers: $ENABLED"
      exit 1
    fi

    # Generate config.yaml
    {
      echo "# Auto-generated by litellm-generate-config"
      echo "# Do not edit — managed by providers-enabled.json"
      echo ""
      echo "model_list:"
      echo "$MODELS" | jq -r '.[] |
        "  - model_name: \(.model_name)\n    litellm_params:\n      model: \(.litellm_params.model)\n      api_base: \(.litellm_params.api_base)\n      api_key: \(.litellm_params.api_key)"
      '
      echo ""
      echo "litellm_settings:"
      echo "  json_logs: true"
      echo "  drop_params: true"
      echo ""
      echo "general_settings:"
      echo "  master_key: os.environ/LITELLM_MASTER_KEY"
    } > "$CONFIG_FILE"

    echo "litellm-generate-config: wrote $CONFIG_FILE with $MODEL_COUNT models"
  '';
in
{
  # Allow the dynamic user to write to dataDir
  systemd.services.litellm.serviceConfig.ReadWritePaths = [
    state.dataDir
  ];

  # Override ExecStart to use our runtime config path
  systemd.services.litellm.serviceConfig.ExecStart = lib.mkForce
    "${lib.getExe config.services.litellm.package} --host \"${config.services.litellm.host}\" --port ${toString config.services.litellm.port} --config ${state.configYaml}";

  # Generate config before service starts (+ = run as root)
  systemd.services.litellm.serviceConfig.ExecStartPre = lib.mkAfter [
    "+${generateConfig}"
  ];
}
